### ISSUE TITLE
Don’t Use Accessor Methods in Initializer Methods and dealloc

### ISSUE THREAD

**Issue by sean7512** [3pillarlabs/ios-PDFexporter#3]
Hello -- Fellow 3Pillar Employee in the US.

I noticed heavy use of `self` in the initializer methods. This should be avoided and the underlying iVar should be used instead.

For example, in PDFPrintPageRenderer.m line 36 and 37 should be changed to:

```
_paperSize = PDFPaperSizeUSLetter;
_paperInsets = kDefaultPaperInsets;
```

For more information, see: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmPractical.html

**Comment by david-livadaru-3pillar** [comment]
It has been fixed in [this](https://github.com/3pillarlabs/ios-PDFexporter/pull/11) pull request.
